apiVersion: v1
kind: Pod
metadata:
   name: test

spec:
  containers:
  - name: nginx
    image: nginx

  - name: mysql
    image: mysql
    env:
      - name: "MYSQL_USER"
        value: "mysql"   
      - name: "MYSQL_PASSWORD"
        value: "mysql"  
      - name: "MYSQL_DATABASE"
        value: "sample"  
      - name: "MYSQL_ROOT_PASSWORD"
        value: "supersecret"  
    ports:
      - containerPort: 3306 
      
  - name: ubuntu
    image: ubuntu
    command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5; done"]
  restartPolicy: Never         
        