#!/usr/bin/env bash

region="us-east-1"
profile="default"
vpc_stackname="AshfaqRehman-VPC" #Active CloudFormation stack name that contains VPC, public and private subnets generated by vpc.sh (pre-req)
ssh_key="OnicaTest" #SSH Key for the EC2 instances

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#aws cloudformation update-stack \
aws cloudformation create-stack \
    --stack-name AshfaqRehman-WebApp \
    --template-body file://${dir}/../cloudformation/webapp.yaml \
    --region ${region} \
    --profile ${profile} \
    --parameters \
        "ParameterKey=NetworkStackName,ParameterValue=${vpc_stackname}" \
        "ParameterKey=KeyName,ParameterValue=${ssh_key}" \
        